# arxivの学問領域の指定
subject: 'cat:astro-ph.*'

# 検索キーワード
keywords:
        Taurus: 1
        Ophiuchus: 1
        Upper Scorpius: 1
        Orion: 1
        Lupus: 1
        Chamaeleon: 1
        circum planetary disk: 1
        disk survey : 1
        Class II: 1
        Class I: 1
        Class 0: 1
        annular substructure: 1
        protostellar: 1
        protostar: 1
        protoplanetary disk: 2
        protoplanetary disc: 2
        circumstellar disk: 1
        circumstellar disc: 1
        disc wind: 1
        disk wind: 1
        protoplanet: 1
        pre-main sequence: 1
        debris disk: 1
        debris disc: 1
        T Tauri star: 1
        transition disk: 1
        transition disc: 1
        planet formation: 1
        dust disk: 1
        dust disc: 1
        gas disk: 1
        gas disc: 1
        radio interferometry: 1
        sparse modeling: 2
        outflow: 1
        protostar: 1
        SETI: 1
# 通知の閾値
score_threshold: 0
