# arxivの学問領域の指定
subject: 'cat:astro-ph.*'

# 検索キーワード
keywords:
        protoplanetary disk: 2
        circumstellar disk: 1
        protoplanet: 1
        pre-main sequence: 1
        debris disk: 1
        T Tauri star: 1
        transition disk: 1
        planet formation: 1
        radio interferometry: 1
        sparse modeling: 2
        protostar: 1
        SETI: 1
# 通知の閾値
score_threshold: 0
